#!/bin/bash

echo "nesox - data transfer scheduling prototype"

cd base 
make libs
cd ..

cd framework
make nesox 
cd ..

cp framework/nesox bin/nesox

if [ -d logs ]; then echo "logs made"; else mkdir logs; fi
if [ -d stat ]; then echo "stat made"; else mkdir stat; fi

echo "build successed!"


