#!/bin/bash

echo "clean building of nesox"

cd base
make clean
cd ..

cd framework
make clean
cd ..

cd bin
rm -rf nesox *.log
cd ..

cd logs
rm -rf *.log
cd ..

cd stat1
rm -rf *
cd ..

cd stat2
rm -rf *
cd ..

echo "clean finished!"

