#!/bin/bash

echo "clean nesox"

cd base
make clean
cd ..

cd framework
make clean
cd ..

cd tools
make clean
cd ..

cd bin
rm -rf nesox compute *.log
cd ..

cd logs
rm -rf *.log
cd ..

cd stat
rm -rf *.*
cd ..

cd heartbeat
rm -rf *.log
cd ..

echo "" > bin/status

echo "clean finished!"
