#!/bin/bash

echo "clean building of nesox"

cd base
make clean
cd ..

cd framework
make clean
cd ..

cd tools
make clean
cd ..

cd bin
rm -rf nesox compute *.log
cd ..

cd logs
rm -rf *.log
cd ..

cd stat
rm -rf *.log
cd ..

cd stat1
rm -rf *logs*
cd ..

cd stat2
rm -rf *.log
cd ..


echo "clean finished!"

